name: Generate PDF

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Pandoc & LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive texlive-xetex texlive-latex-extra

      - name: Convert index.md to index.pdf
        run: |
          if [[ -f "index.md" ]]; then
            pandoc index.md -o index.pdf --template=templates/ph-simple.tex --pdf-engine=xelatex --from markdown-yaml_metadata_block
            echo "Successfully converted 'index.md' to 'index.pdf'."
          else
            echo "Couldn't find 'index.md'."
            exit 1
          fi

      - name: Upload PDF as artifact.
        uses: actions/upload-artifact@v3
        with:
          name: resume-pdf
          path: index.pdf
